version: "3"

services:
  suricata:
    build: ./suricata
    image: anssi/shovel-suricata:dev
    volumes:
      - "./input_pcaps:/input_pcaps:ro"
      - "./suricata/rules:/suricata/rules:ro"
      - "./suricata/output:/suricata/output:rw"
    env_file:
      - .env

  webapp:
    build: ./webapp
    image: anssi/shovel-webapp:dev
    volumes:
      - "./input_pcaps:/webapp/static/input_pcaps:ro"
      - "./suricata/output:/suricata/output:ro"
      - "./webapp/database:/webapp/database:rw"
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env

  grafana:
    build: ./grafana
    image: anssi/shovel-grafana:dev
    volumes:
      - "./webapp/database:/webapp/database:ro"
    ports:
      - 127.0.0.1:3000:3000
