# Copyright (C) 2024  ANSSI
# SPDX-License-Identifier: CC0-1.0
apiVersion: 1

datasources:
  - name: SQLite
    type: frser-sqlite-datasource
    jsonData:
      path: /webapp/database/database.db
    isDefault: true
