name: Publish Docker image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - '*'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./webapp
            image: anssi/shovel-webapp
            platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le
          - context: ./suricata
            image: anssi/shovel-suricata
            platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le
          - context: ./grafana
            image: anssi/shovel-grafana
            platforms: linux/amd64,linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
        with:
          platforms: "arm,arm64,s390x,ppc64le"
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
